pub const MnemeError = error{
    InvalidDimension,
    EmptyVector,
    ZeroVector,
    DuplicateId,
    IdNotFound,
    InvalidMagic,
    UnsupportedVersion,
    InvalidMetric,
    InvalidIndexConfig,
    InvalidEfSearch,
    TruncatedFile,
    CorruptRecord,
    VectorLengthMismatch,
    IndexNotBuilt,
    IndexStale,
};
