name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Zig version
        run: zig version

      - name: Lint
        run: zig build lint

      - name: Format check
        run: zig fmt --check .

      - name: Test
        run: zig build test
